name: Build on macos-26

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk
        path: ${{github.workspace}}/build/libjdk*.tar.gz

  build-repo:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DJ=5 -DINSTAll_TO_REPO=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-repo
        path: ${{github.workspace}}/build/libjdk*.tar.gz